version: '3'

services:
  bouncer:
    container_name: Bouncer
    deploy:
      restart_policy:
        condition: any
    environment:
      SENTRY_DSN: SENTRY_DSN_FOR_ERROR_REPORTING
      SUPPORT_SERVER: ID_OF_SUPPORTSERVER
      TOKEN: BOT_TOKEN
      OWNER_ID: DISCORD_ID_OF_OWNER
      LOG_LEVEL: Info
    image: ghcr.io/serpensin/discordbots-bouncer:latest
    volumes:
    - bouncer:/app/Bouncer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "5000:5000"

volumes:
    bouncer: